[project]
name = "13-home-work"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.119.0",
    "fastapi-mail>=1.5.0",
    "pydantic-settings>=2.11.0",
]
