class ContactCRUD:
    async def create_contact(self, body):
        ...

    async def read_contact(self, body):
        ...

    async def update_contact(self, body):
        ...

    async def delete_contact(self, body):
        ...